# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#https://dev.azure.com/gstarczewski/jmeter/_apis/build/builds?api-version=5.1
name: $(BuildID)
trigger:
  - master
jobs:
  - job: Run_Jmeter_Tests
    pool:
      vmImage: 'ubuntu-latest'

    timeoutInMinutes: 5
    steps:
      - task: Maven@3
        displayName: Run_JMeter_Tests_WithMaven
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'verify'

      - task: CmdLine@2
        displayName: List_JMeter_ReportDir
        inputs:
          script: 'ls -alh $(System.DefaultWorkingDirectory)/target/jmeter/reports'

      - script: 'pip install chart_studio requests'
        displayName: Install_Python_Libs

      - task: PythonScript@0
        displayName: Fetch Reports For Last Successful Builds
        inputs:
          scriptSource: 'filePath'
          scriptPath: $(System.DefaultWorkingDirectory)/target/getLastBuildsWithArtifacts.py

      - task: CmdLine@2
        displayName: List_Last_Reports
        inputs:
          script: 'ls -alh $(System.DefaultWorkingDirectory)/target/tmp'

      - task: PythonScript@0
        displayName: Run Trend Reports
        inputs:
          scriptSource: 'filePath'
          scriptPath: $(System.DefaultWorkingDirectory)/target/trend_charts.py

      - task: PublishPipelineArtifact@1
        displayName: Archive_JMeter_Report
        inputs:
          path: $(System.DefaultWorkingDirectory)/target/jmeter/reports
          artifact: JmeterReport